using System;
using System.Reflection;
using System.Runtime.InteropServices;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NAnt")]
[assembly: AssemblyDescriptionAttribute("A .NET Build Tool")]
[assembly: AssemblyConfigurationAttribute("dev")]
[assembly: AssemblyCompanyAttribute("http://nant.sourceforge.net")]
[assembly: AssemblyProductAttribute("NAnt")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2001-2012 Gerry Shaw")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("0.93.4697.0")]
[assembly: AssemblyInformationalVersionAttribute("0.93")]

